spring.application.name=customer-api
server.port=8080
spring.config.import=optional:file:../.env[.properties]

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
app.kafka.topic=customer-topic
spring.data.mongodb.uri=mongodb://admin:admin123@localhost:27017/customer_pipeline?authSource=admin

spring.datasource.driver-class-name=net.snowflake.client.jdbc.SnowflakeDriver
spring.datasource.url=jdbc:snowflake://${SNOWFLAKE_ID}.snowflakecomputing.com/?warehouse=COMPUTE_WH&db=SNOWFLAKE_SAMPLE_DATA&schema=TPCDS_SF10TCL&JDBC_QUERY_RESULT_FORMAT=JSON
spring.datasource.username=${SNOWFLAKE_USERNAME}
spring.datasource.password=${SNOWFLAKE_PASSWORD}

