```sql
USE DATABASE SNOWFLAKE_SAMPLE_DATA;
USE SCHEMA TPCDS_SF10TCL;

SELECT COUNT(*) FROM CUSTOMER;

SELECT
    C.C_CUSTOMER_SK AS CUSTOMER_ID,
    C.C_FIRST_NAME AS FIRST_NAME,
    C.C_LAST_NAME AS LAST_NAME,
    C.C_BIRTH_DAY AS BIRTH_DAY,
    C.C_BIRTH_MONTH AS BIRTH_MONTH,
    C.C_BIRTH_YEAR AS BIRTH_YEAR,
    C.C_EMAIL_ADDRESS AS EMAIL,
    CA.CA_STREET_NAME AS STREET,
    CA.CA_STREET_NUMBER AS STREET_NUMBER,
    CA.CA_CITY AS CITY,
    CA.CA_STATE AS STATE,
    CA.CA_COUNTRY AS COUNTRY
FROM CUSTOMER C
LEFT JOIN CUSTOMER_ADDRESS CA
    ON C.C_CURRENT_ADDR_SK = CA.CA_ADDRESS_SK
ORDER BY C.C_CUSTOMER_SK
LIMIT 10;
```
